/**
 * @package shared
 * @name domain-common.schema.ts
 * @version 0.0.1
 * @description Define contratos transversales de timestamp, origen de actualización y trazabilidad de dominio.
 * @author @tirsomartinezreyes
 * @changelog
 * - 0.0.1	(2026-04-14)	Versión inicial del archivo.	@tirsomartinezreyes
 */

import { z } from 'zod';
import { RoleSchema } from './access.schema';

export const TimestampMillisecondsUtcSchema = z.number().int().nonnegative().safe();

export const UPDATE_ORIGIN = {
  SYSTEM: 'SYSTEM',
  USER: 'USER',
  PUI: 'PUI'
} as const;

export const UpdateOriginValues = [
  UPDATE_ORIGIN.SYSTEM,
  UPDATE_ORIGIN.USER,
  UPDATE_ORIGIN.PUI
] as const;
export const UpdateOriginSchema = z.enum(UpdateOriginValues);

export const UpdateActorSchema = z.object({
  updateOrigin: UpdateOriginSchema,
  updatedByUserId: z.string().min(1).nullable().optional(),
  updatedByUserRole: RoleSchema.nullable().optional(),
  updatedByUserEmail: z.string().email().nullable().optional(),
  updatedAt: TimestampMillisecondsUtcSchema
});

export const LOG_ORIGIN = {
  SYSTEM_HTTP_API_CALL: 'SYSTEM_HTTP_API_CALL',
  SYSTEM_AUTH_TRIGGER: 'SYSTEM_AUTH_TRIGGER',
  SYSTEM_STORAGE_TRIGGER: 'SYSTEM_STORAGE_TRIGGER',
  SYSTEM_DATA_TRIGGER: 'SYSTEM_DATA_TRIGGER'
} as const;

export const LogOriginValues = [
  LOG_ORIGIN.SYSTEM_HTTP_API_CALL,
  LOG_ORIGIN.SYSTEM_AUTH_TRIGGER,
  LOG_ORIGIN.SYSTEM_STORAGE_TRIGGER,
  LOG_ORIGIN.SYSTEM_DATA_TRIGGER
] as const;
export const LogOriginSchema = z.enum(LogOriginValues);

export const LOG_CATEGORIES = {
  INSTITUTION_CREATION: 'INSTITUTION_CREATION',
  INSTITUTION_PLAN_CREATION: 'INSTITUTION_PLAN_CREATION',
  INSTITUTION_PLAN_UPDATE: 'INSTITUTION_PLAN_UPDATE',
  INSTITUTION_CONTACT_CREATION: 'INSTITUTION_CONTACT_CREATION',
  INSTITUTION_CONTACT_UPDATE: 'INSTITUTION_CONTACT_UPDATE',
  INSTITUTION_SHARED_SECRET_UPDATE: 'INSTITUTION_SHARED_SECRET_UPDATE',
  INSTITUTION_PERMISSION_CREATION: 'INSTITUTION_PERMISSION_CREATION',
  INSTITUTION_PERMISSION_UPDATE: 'INSTITUTION_PERMISSION_UPDATE',
  INSTITUTION_SEARCH_REQUEST_PHASE_CHANGE: 'INSTITUTION_SEARCH_REQUEST_PHASE_CHANGE',
  INSTITUTION_SEARCH_REQUEST_PHASE_STATUS_CHANGE: 'INSTITUTION_SEARCH_REQUEST_PHASE_STATUS_CHANGE',
  INSTITUTION_SEARCH_REQUEST_MATCH_FOUND: 'INSTITUTION_SEARCH_REQUEST_MATCH_FOUND',
  PUI_SEARCH_REQUEST_CREATION: 'PUI_SEARCH_REQUEST_CREATION',
  PUI_SEARCH_REQUEST_REVOCATION: 'PUI_SEARCH_REQUEST_REVOCATION',
  PUI_SEARCH_REQUEST_HISTORICAL_FINISH: 'PUI_SEARCH_REQUEST_HISTORICAL_FINISH',
  PUI_SEARCH_REQUEST_MATCH: 'PUI_SEARCH_REQUEST_MATCH',
  PUI_SEARCH_REQUEST_API_ERROR: 'PUI_SEARCH_REQUEST_API_ERROR',
  PUI_FINDING_SYNC_SUCCESS: 'PUI_FINDING_SYNC_SUCCESS',
  PUI_FINDING_SYNC_ERROR: 'PUI_FINDING_SYNC_ERROR',
  PUI_FINDING_SYNC_RESCHEDULE: 'PUI_FINDING_SYNC_RESCHEDULE',
  USER_ACCOUNT_CREATION: 'USER_ACCOUNT_CREATION',
  USER_ACCOUNT_LOGIN: 'USER_ACCOUNT_LOGIN',
  USER_ACCOUNT_LOGOUT: 'USER_ACCOUNT_LOGOUT',
  USER_ACCOUNT_PASSWORD_RECOVERY_REQUEST: 'USER_ACCOUNT_PASSWORD_RECOVERY_REQUEST', //NOSONAR - No es una vulnerabilidad, solo un evento de solicitud de recuperación de contraseña
  USER_ACCOUNT_PASSWORD_UPDATE: 'USER_ACCOUNT_PASSWORD_UPDATE', //NOSONAR - No es una vulnerabilidad, solo un evento de actualización de contraseña
  USER_ACCOUNT_EMAIL_VERIFICATION: 'USER_ACCOUNT_EMAIL_VERIFICATION',
  USER_ACCOUNT_MFA_ENROLL: 'USER_ACCOUNT_MFA_ENROLL',
  USER_ACCOUNT_MFA_UNENROLL: 'USER_ACCOUNT_MFA_UNENROLL',
  USER_ACCOUNT_SETTINGS_UPDATE: 'USER_ACCOUNT_SETTINGS_UPDATE'
} as const;

export const LogCategoryValues = [
  LOG_CATEGORIES.INSTITUTION_CREATION,
  LOG_CATEGORIES.INSTITUTION_PLAN_CREATION,
  LOG_CATEGORIES.INSTITUTION_PLAN_UPDATE,
  LOG_CATEGORIES.INSTITUTION_CONTACT_CREATION,
  LOG_CATEGORIES.INSTITUTION_CONTACT_UPDATE,
  LOG_CATEGORIES.INSTITUTION_SHARED_SECRET_UPDATE,
  LOG_CATEGORIES.INSTITUTION_PERMISSION_CREATION,
  LOG_CATEGORIES.INSTITUTION_PERMISSION_UPDATE,
  LOG_CATEGORIES.INSTITUTION_SEARCH_REQUEST_PHASE_CHANGE,
  LOG_CATEGORIES.INSTITUTION_SEARCH_REQUEST_PHASE_STATUS_CHANGE,
  LOG_CATEGORIES.INSTITUTION_SEARCH_REQUEST_MATCH_FOUND,
  LOG_CATEGORIES.PUI_SEARCH_REQUEST_CREATION,
  LOG_CATEGORIES.PUI_SEARCH_REQUEST_REVOCATION,
  LOG_CATEGORIES.PUI_SEARCH_REQUEST_HISTORICAL_FINISH,
  LOG_CATEGORIES.PUI_SEARCH_REQUEST_MATCH,
  LOG_CATEGORIES.PUI_SEARCH_REQUEST_API_ERROR,
  LOG_CATEGORIES.PUI_FINDING_SYNC_SUCCESS,
  LOG_CATEGORIES.PUI_FINDING_SYNC_ERROR,
  LOG_CATEGORIES.PUI_FINDING_SYNC_RESCHEDULE,
  LOG_CATEGORIES.USER_ACCOUNT_CREATION,
  LOG_CATEGORIES.USER_ACCOUNT_LOGIN,
  LOG_CATEGORIES.USER_ACCOUNT_LOGOUT,
  LOG_CATEGORIES.USER_ACCOUNT_PASSWORD_RECOVERY_REQUEST,
  LOG_CATEGORIES.USER_ACCOUNT_PASSWORD_UPDATE,
  LOG_CATEGORIES.USER_ACCOUNT_EMAIL_VERIFICATION,
  LOG_CATEGORIES.USER_ACCOUNT_MFA_ENROLL,
  LOG_CATEGORIES.USER_ACCOUNT_MFA_UNENROLL,
  LOG_CATEGORIES.USER_ACCOUNT_SETTINGS_UPDATE
] as const;

export const LogCategorySchema = z.enum(LogCategoryValues);

export type UpdateOrigin = z.infer<typeof UpdateOriginSchema>;
export type UpdateActor = z.infer<typeof UpdateActorSchema>;
export type LogOrigin = z.infer<typeof LogOriginSchema>;
export type LogCategory = z.infer<typeof LogCategorySchema>;
