sonar.organization=tu-org-en-sonarcloud
sonar.projectKey=tu-org_puintegra
sonar.projectName=PUIntegra

sonar.sources=packages/shared/src,packages/api/src,packages/web/src
sonar.tests=packages/shared/tests,packages/api/tests,packages/web/tests
sonar.exclusions=**/generated/**,**/node_modules/**,**/*.spec.ts

sonar.javascript.lcov.reportPaths=packages/shared/coverage/lcov.info,packages/api/coverage/lcov.info,packages/web/coverage/lcov.info

sonar.typescript.cognitive_complexity.threshold=15
sonar.javascript.environments=node,browser
sonar.typescript.tsconfigPath=tsconfig.json
