sonar.organization=esimios
sonar.projectKey=ESIMIOS_PUIntegra
sonar.projectName=PUIntegra
sonar.sourceEncoding=UTF-8

sonar.sources=packages/shared/src,packages/api/src,packages/web/src
sonar.tests=packages/shared/tests,packages/api/tests,packages/web/tests
sonar.exclusions=**/generated/**,**/node_modules/**,**/dist/**,**/coverage/**,**/*.spec.ts,**/*.test.ts
sonar.coverage.exclusions=**/*.test.ts,**/*.spec.ts,**/tests/**,**/vite-env.d.ts

sonar.javascript.lcov.reportPaths=packages/shared/coverage/lcov.info,packages/api/coverage/lcov.info,packages/web/coverage/lcov.info

sonar.architecture.definitionPath=sonar-architecture.yaml

sonar.typescript.cognitive_complexity.threshold=15
sonar.javascript.environments=node,browser
sonar.typescript.tsconfigPath=tsconfig.base.json,packages/web/tsconfig.json,packages/api/tsconfig.json,packages/shared/tsconfig.json
