name: Deploy — Production

on:
  push:
    branches:
      - main

jobs:
  deploy-production:
    name: Build & Deploy to Production
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@08c4be7e2e672a47d11bd04269e27e5f3e8529cb # v6.0.0
        # version read automatically from packageManager field in package.json

      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: pnpm

      - name: Install dependencies
        #SONARQUBE: --ignore-scripts should not be used here because we need to run the postinstall scripts to build native dependencies like esbuild, there are white-listed in the root package.json using onlyBuiltDependencies
        run: pnpm install --frozen-lockfile #NOSONAR

      - name: Build (production mode)
        run: pnpm --filter web build -- --mode production
        env:
          VITE_SENTRY_RELEASE: ${{ github.sha }}

      - name: Deploy to Firebase (production)
        uses: FirebaseExtended/action-hosting-deploy@e2eda2e106cfa35cdbcf4ac9ddaf6c4756df2c8c # v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_PRODUCTION }}
          projectId: puintegra-production
          channelId: live
